#pragma once


#undef __HAL_RCC_GPIOD_CLK_ENABLE
#define __HAL_RCC_GPIOD_CLK_ENABLE()

#undef __HAL_RCC_GPIOA_CLK_ENABLE
#define __HAL_RCC_GPIOA_CLK_ENABLE()

#undef __HAL_RCC_GPIOB_CLK_ENABLE
#define __HAL_RCC_GPIOB_CLK_ENABLE()

#undef __HAL_RCC_SPI2_CLK_ENABLE
#define __HAL_RCC_SPI2_CLK_ENABLE()

#undef __HAL_RCC_USART1_CLK_ENABLE
#define __HAL_RCC_USART1_CLK_ENABLE()

#undef __HAL_RCC_AFIO_CLK_ENABLE
#define __HAL_RCC_AFIO_CLK_ENABLE()

#undef __HAL_RCC_PWR_CLK_ENABLE
#define __HAL_RCC_PWR_CLK_ENABLE()
